version: '2'
services:
  pgmaster:
     image: 10.0.0.96:5000/database/pg_ip_pglogical_pathman:v3 
     hostname: pgmaster
     labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: key1=100
     networks: 
       - docker_gwbridge
     ports:
       - "30000:5432"
     volumes:
       - /opt/pgmaster/pgdata/data:/var/lib/pgsql/9.6/data
     privileged: true
     tty: true

